import { Zap, RefreshCw, Globe, Lock, Terminal, GitBranch } from 'lucide-react';

const FEATURES = [
  {
    icon: Zap,
    title: 'Instant generation',
    description: 'From prompt to working app in under 30 seconds. No waiting, no setup.',
    color: 'text-blue-400',
    bg: 'bg-blue-500/8',
  },
  {
    icon: RefreshCw,
    title: 'Real-time iteration',
    description: 'Edit your app with follow-up prompts. AI understands context and applies changes instantly.',
    color: 'text-sky-400',
    bg: 'bg-sky-500/8',
  },
  {
    icon: Globe,
    title: 'One-click deploy',
    description: 'Deploy to a live URL instantly. Share with anyone, anywhere, no configuration needed.',
    color: 'text-green-400',
    bg: 'bg-green-500/8',
  },
  {
    icon: Terminal,
    title: 'Full-stack ready',
    description: 'Frontend, backend, database, and auth all generated together and wired up automatically.',
    color: 'text-orange-400',
    bg: 'bg-orange-500/8',
  },
  {
    icon: GitBranch,
    title: 'Export your code',
    description: 'Own your code completely. Export clean, production-quality code to any repo at any time.',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/8',
  },
  {
    icon: Lock,
    title: 'Built-in security',
    description: 'Auth, RLS policies, and secure API routes are generated by default — not as an afterthought.',
    color: 'text-red-400',
    bg: 'bg-red-500/8',
  },
];

export default function Features() {
  return (
    <section id="features" className="py-28 px-6">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-16">
          <p className="text-xs font-medium text-blue-400 uppercase tracking-widest mb-4">Features</p>
          <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight">
            Everything you need to ship fast
          </h2>
          <p className="text-white/40 mt-4 max-w-lg mx-auto text-sm leading-relaxed">
            withaibuild handles the entire stack so you can focus on what matters — building your product.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURES.map(({ icon: Icon, title, description, color, bg }) => (
            <div
              key={title}
              className="card-hover bg-[#0d0d0d] border border-white/6 rounded-2xl p-6"
            >
              <div className={`w-10 h-10 ${bg} rounded-xl flex items-center justify-center mb-4`}>
                <Icon size={18} className={color} />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">{title}</h3>
              <p className="text-xs text-white/40 leading-relaxed">{description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
