import { Zap, Star, Wrench, AlertCircle } from 'lucide-react';
import { usePageLoader } from '../hooks/usePageLoader';
import PageSkeleton from '../components/PageSkeleton';

const ENTRIES = [
  {
    version: 'v1.4.0',
    date: 'February 17, 2026',
    badge: 'Major release',
    badgeColor: 'bg-blue-500/15 text-blue-400',
    items: [
      { type: 'new', text: 'Template library launched — 50+ production-ready app templates across 8 categories' },
      { type: 'new', text: 'Team collaboration: invite teammates to projects, real-time presence indicators' },
      { type: 'new', text: 'Custom domains now available on Pro and Team plans' },
      { type: 'new', text: 'GitHub sync — automatically push to a repo on every deploy' },
      { type: 'improved', text: 'AI generation speed improved by 40% across all project types' },
      { type: 'improved', text: 'Sidebar navigation is now collapsible and persists state in localStorage' },
      { type: 'fixed', text: 'Fixed an issue where real-time subscriptions would occasionally drop on reconnect' },
    ],
  },
  {
    version: 'v1.3.2',
    date: 'February 3, 2026',
    badge: 'Patch',
    badgeColor: 'bg-green-500/15 text-green-400',
    items: [
      { type: 'fixed', text: 'Resolved a race condition in auth state management on page load' },
      { type: 'fixed', text: 'Edge Function cold start latency reduced from 300ms to under 50ms' },
      { type: 'fixed', text: 'Mobile preview panel now correctly renders on devices with notch' },
      { type: 'improved', text: 'Error messages in the builder are now more actionable with suggested fixes' },
    ],
  },
  {
    version: 'v1.3.0',
    date: 'January 22, 2026',
    badge: 'Minor release',
    badgeColor: 'bg-sky-500/15 text-sky-400',
    items: [
      { type: 'new', text: 'Code diff viewer — see exactly which files changed after each generation' },
      { type: 'new', text: 'Multi-file editor: browse and manually edit any file in your project' },
      { type: 'new', text: 'Deployment history with one-click rollback to any previous version' },
      { type: 'new', text: 'Environment variables management UI in project settings' },
      { type: 'improved', text: 'Database schema viewer now shows foreign key relationships as a visual diagram' },
      { type: 'fixed', text: 'PDF export in generated apps now works correctly in Chromium-based browsers' },
    ],
  },
  {
    version: 'v1.2.0',
    date: 'January 8, 2026',
    badge: 'Minor release',
    badgeColor: 'bg-sky-500/15 text-sky-400',
    items: [
      { type: 'new', text: 'Real-time subscriptions: prompts that include "live updates" now generate Supabase Realtime listeners automatically' },
      { type: 'new', text: 'CSV and PDF export helpers added to the generated code utilities' },
      { type: 'new', text: 'Dark/light mode toggle is now generated automatically when mentioned in the prompt' },
      { type: 'improved', text: 'Row Level Security policies are now explained inline in generated migration files' },
      { type: 'improved', text: 'TypeScript types are now auto-generated from the Supabase schema on every build' },
    ],
  },
  {
    version: 'v1.1.0',
    date: 'December 19, 2025',
    badge: 'Minor release',
    badgeColor: 'bg-sky-500/15 text-sky-400',
    items: [
      { type: 'new', text: 'Iterative prompting — follow-up prompts now apply targeted diffs instead of regenerating the whole app' },
      { type: 'new', text: 'Mobile-responsive layouts generated by default on all apps' },
      { type: 'new', text: 'Supabase Edge Functions support for server-side logic' },
      { type: 'improved', text: 'Initial generation time reduced from 45s to under 20s on average' },
      { type: 'fixed', text: 'Fixed form validation not triggering on blur in generated components' },
    ],
  },
  {
    version: 'v1.0.0',
    date: 'December 1, 2025',
    badge: 'Initial launch',
    badgeColor: 'bg-white/10 text-white/50',
    items: [
      { type: 'new', text: 'withaibuild is live — generate full-stack React apps from natural language prompts' },
      { type: 'new', text: 'PostgreSQL schema generation with automatic RLS policies' },
      { type: 'new', text: 'Email/password authentication included in every app with a login flow' },
      { type: 'new', text: 'One-click deployment to withaibuild.com subdomains' },
      { type: 'new', text: 'Code export to download full project as a zip' },
    ],
  },
];

const TYPE_CONFIG = {
  new: { icon: Star, color: 'text-blue-400', bg: 'bg-blue-500/10', label: 'New' },
  improved: { icon: Zap, color: 'text-green-400', bg: 'bg-green-500/10', label: 'Improved' },
  fixed: { icon: Wrench, color: 'text-amber-400', bg: 'bg-amber-500/10', label: 'Fixed' },
  breaking: { icon: AlertCircle, color: 'text-red-400', bg: 'bg-red-500/10', label: 'Breaking' },
};

export default function ChangelogPage() {
  const loading = usePageLoader();
  if (loading) return <PageSkeleton />;
  return (
    <div className="min-h-screen bg-[#080808] pt-24 pb-24 px-6">
      <div className="max-w-2xl mx-auto">
        <div className="mb-14">
          <p className="text-xs font-medium text-blue-400 uppercase tracking-widest mb-3">Changelog</p>
          <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-4">
            What's new in withaibuild
          </h1>
          <p className="text-white/40 text-sm max-w-md leading-relaxed">
            Every release, improvement, and fix — documented in one place.
          </p>
        </div>

        <div className="relative">
          <div className="absolute left-[11px] top-2 bottom-2 w-px bg-white/6" />

          <div className="space-y-14">
            {ENTRIES.map((entry) => (
              <div key={entry.version} className="relative pl-8">
                <div className="absolute left-0 top-1.5 w-[23px] h-[23px] rounded-full bg-[#080808] border-2 border-white/15 flex items-center justify-center">
                  <div className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                </div>

                <div className="flex flex-wrap items-center gap-3 mb-5">
                  <h2 className="text-lg font-bold text-white">{entry.version}</h2>
                  <span className={`text-xs px-2.5 py-1 rounded-full font-medium ${entry.badgeColor}`}>
                    {entry.badge}
                  </span>
                  <span className="text-xs text-white/30">{entry.date}</span>
                </div>

                <ul className="space-y-3">
                  {entry.items.map((item, idx) => {
                    const cfg = TYPE_CONFIG[item.type as keyof typeof TYPE_CONFIG];
                    const Icon = cfg.icon;
                    return (
                      <li key={idx} className="flex items-start gap-3">
                        <div className={`w-5 h-5 rounded-md ${cfg.bg} flex items-center justify-center flex-shrink-0 mt-0.5`}>
                          <Icon size={10} className={cfg.color} />
                        </div>
                        <div className="flex items-start gap-2 flex-1">
                          <span className={`text-xs font-semibold ${cfg.color} mt-0.5 flex-shrink-0`}>
                            {cfg.label}
                          </span>
                          <p className="text-sm text-white/55 leading-relaxed">{item.text}</p>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
